import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Newpage Consult",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-800`}
      >
        <Header/>
        {children}
        <div id="actionWh">
          <a href="https://wa.me/2348034786633?text=Hi,%20this%20is%20coming%20from%20the%20website,%20I'm%20interested%20in%20knowing%20details%20about%20"><i className="fa-brands fa-whatsapp fa-3x" aria-hidden="true" style={{color: "green", fontWeight: 800}}></i></a>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
